# Generated by Django 3.2.18 on 2023-03-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0007_alter_uav_options'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uav',
        ),
        migrations.AddField(
            model_name='order',
            name='uav',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='uav.uav'),
            preserve_default=False,
        ),
    ]
