# Generated by Django 3.2.18 on 2023-03-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=155, verbose_name='category_name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=155, verbose_name='category_name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Uav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('weight', models.FloatField(default=0, verbose_name='weight')),
                ('endurance', models.FloatField(default=0, verbose_name='endurance')),
                ('flight_range', models.FloatField(default=0, verbose_name='flight range')),
                ('max_speed', models.PositiveIntegerField(default=0, verbose_name='max_speed')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uavs', to='uav.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uavs', to='uav.category')),
            ],
            options={
                'verbose_name': 'uav',
                'verbose_name_plural': 'uavs',
            },
        ),
        migrations.CreateModel(
            name='UavMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uav')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='uav.uav')),
            ],
            options={
                'verbose_name': 'uav media',
                'verbose_name_plural': 'uav medias',
            },
        ),
    ]
