# Generated by Django 3.2.18 on 2023-03-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
