# Generated by Django 3.2.18 on 2023-03-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0002_uav_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uav'),
        ),
        migrations.DeleteModel(
            name='UavMedia',
        ),
    ]
