# Generated by Django 3.2.18 on 2023-03-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0003_auto_20230320_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='image',
            field=models.ImageField(blank=True, default='src/media/default.jpg', null=True, upload_to='uav'),
        ),
    ]
