# Generated by Django 3.2.18 on 2023-03-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0004_alter_uav_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uav',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='uav'),
        ),
    ]
