# Generated by Django 3.2.18 on 2023-03-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0005_alter_uav_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
