# Generated by Django 3.2.18 on 2023-03-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uav', '0006_uav_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uav',
            options={'ordering': ('pk',), 'verbose_name': 'uav', 'verbose_name_plural': 'uavs'},
        ),
    ]
