version: '3.3'

services:
  db:
    image: library/postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "54030:5432"
    networks:
      - uav-rental-network
    env_file:
      - ./src/.env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  web:
    build: ./src
    networks:
      - uav-rental-network
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn uav_rental.wsgi:application --bind 0.0.0.0:9515 --workers 4"
    volumes:
      - ./src:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "9515:9515"
    env_file:
      - ./src/.env
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  static_volume:  
    driver: local
  media_volume:  
    driver: local

networks:
  uav-rental-network:
    driver: bridge