version: '3.9'

services:
  db:
    image: library/postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "55036:5432"
    networks:
      - uav-rental-network
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  web:
    build: ./src
    networks:
      - uav-rental-network
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn main.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - ./src:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  static_volume:  
    driver: local
  media_volume:  
    driver: local

networks:
  uav-rental-network:
    driver: bridge